# Project information
site_name: Amazing List ™
site_url: https://andriksantos.github.io/amazinglist/
site_author: Andrik Santos ™
site_description: >-
    Compilation of programming resources to boost your career in the world of software development. Amazing lists on all kinds of cool topics, awesome framework, libraries, software and resources for your off-limits project!

#Menu
nav:
    - Home: index.md
    - Code of conduct: code-of-conduct.md
    - Contributing: contributing.md
    - License: license.md
    - About: about.md
    - Thanks: thanks.md

# Repository
repo_name: andriksantos/amazinglist
repo_url: https://github.com/andriksantos/amazinglist
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2021 Andrik Santos ™'

#Configuration
theme: material

favicon: assets/favicon.png
icon:
  logo: logo

# Static files
static_templates:
    - 404.html

# Don't include MkDocs' JavaScript
include_search_page: true
search_index_only: true

markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html

# Social Networks
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://andriksantos.github.io/
      name: Go to my repository on github
    - icon: fontawesome/brands/twitter
      link: https://www.twitter.com/andrik_rsm/
      name: Follow me on twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/andriksantos/
      name: Follow me on linkedin
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/andriksantos1/
      name: andriksantos1 on instagram

# Google Analytics
google_analytics:
  - 'UA-169388687-1'
  - 'auto'