# Project information
site_name: Developer Resources | Keebox List â„¢
site_url: https://andriksantos.github.io/keebox/
site_author: Andrik Santos â„¢
site_description: >-
    This repository is a valuable resource for anyone looking to boost their career in software development. ðŸ’¡ The division of resources by programming language makes it easy to find the information you need, and the focus on including frameworks, libraries, and other resources makes it a comprehensive resource for all types of projects. off-limits project!

#Menu
nav:
    - Resources of programming: index.md
    - Npm: npm.md
    - Ios: ios.md
    - Mac: mac.md
    - Swift: Swift.md
    - Node.js: nodejs.md
    - Electron: electron.md
    - Contributing: contributing.md
    - Code of conduct: code-of-conduct.md
    - Donate: donate.md

# Repository
repo_name: andriksantos/keebox
repo_url: https://github.com/andriksantos/keebox
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2033 Andrik Santos â„¢'

#Configuration
theme: 
  name: material

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    #- navigation.tabs
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

favicon: assets/favicon.png
icon:
  logo: logo

markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html

# Social Networks
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://andriksantos.github.io/
      name: Visit my portfolio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/andriksantos/
      name: Follow me on linkedin

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Spanish
      link: /es/
      lang: es
    - name: Chinese (Traditional)
      link: /zh-Hant/
      lang: zh-Hant

extra:
  analytics:
    provider: google
    property: G-NS99JL93ZV